# -*- coding: utf-8 -*-
"""rainfall_predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/153Qg1IfZ0V8IsnwR2hAVRKwgj9F9SiOC

**Importing** **Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, confusion_matrix, accuracy_score

"""**Data** **Processing** **and Model Training**"""

data = pd.read_csv("Austin-2019-01-01-to-2023-07-22.csv")
feature = ["tempmax","tempmin","temp", "humidity", "dew", "windspeed", "cloudcover"]
target = "precip"
data = data.dropna(subset = feature +[target])
X = data[feature]
Y = data[target]
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state = 42)
model = LinearRegression()
model.fit(X_train,Y_train)

"""**Pedicted Value**"""

y_pred = model.predict(X_test)
y_pred

"""**Error in Model**"""

mse = mean_squared_error(Y_test,y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test,y_pred)
print(f"Mean Squared Error: {mse}")
print(f"Root Mean Squared Error: {rmse}")
print(f"R-squared: {r2}")

"""**EDA**"""

sns.set(style = "whitegrid")
plt.figure(figsize=(15,10))
cols = ["tempmax","tempmin","temp", "humidity", "dew", "windspeed", "cloudcover"]
for i,col in enumerate(cols,1):
  plt.subplot(4,2,i)
  plt.title(f"Distribution of {col}")
  sns.histplot(data[col], kde=True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
sns.heatmap(data[cols].corr(),annot =True , cmap = "coolwarm")
plt.title("Correlation Graph")
plt.show()